const learnData = [
  {
    id: 1,
    name: "How to Make a Flyer: The Ultimate Guide to Flyer Design",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/03/how-to-make-a-flyer.jpg",
    desc: "Before we dive into the detailed steps let’s have quick steps to make a flyer. How To Make a Flyer Picture this: You have a brilliant idea for an event, … ",
    path: "/learn-details",
  },
  {
    id: 2,
    name: "Brochure Design Ideas",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/04/345-1-735x400.jpg",
    desc: "Brochures are an essential marketing tool that allows businesses and organizations to effectively communicate their products, services, or ideas to their target audience. Also, a well-designed brochure can captivate the … ",
    path: "/learn-details",
  },
  {
    id: 3,
    name: "Restaurant Brochure Examples: 14+ Printable Templates",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/10/656-Restaurant-Brochure-Examples-1.jpg",
    desc: "Do you run a restaurant and want to make cool brochures to attract more customers? Sometimes, finding good restaurant brochure examples can be tricky. You might be thinking, “How do …  ",
    path: "/learn-details",
  },
  {
    id: 4,
    name: "Best Certificate Layout Design Ideas",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/04/258-735x400.jpg",
    desc: "Certificates are often given as a recognition or reward for achieving a milestone or goal. The design of a certificate is also important as it reflects the value and importance …  ",
    path: "/learn-details",
  },
  {
    id: 5,
    name: "Certificate Samples: Design and Impact",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/10/Certificate-Sample-1.jpg",
    desc: "Are you struggling to create the perfect certificate for your event or achievement? You’re not alone! Crafting an impressive certificate can be a real challenge, especially if you’re not a … ",
    path: "/learn-details",
  },
  {
    id: 6,
    name: "How to Add a QR Code to a Flyer",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/08/How-To-Add-A-Qr-Code-To-A-Flyer-735x400.jpg",
    desc: "Flyers have long been a versatile marketing tool, but with the integration of QR codes, their potential has expanded even further. Adding QR codes to your flyers can add a … ",
    path: "/learn-details",
  },
  {
    id: 7,
    name: "Types of Fonts: Exploring the World of Typography",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/08/Types-Of-Fonts-735x400.jpg",
    desc: "Typography is more than just arranging letters on a page. It’s an art form that conveys messages, evokes emotions, and sets the tone for any written content. Types of fonts, … ",
    path: "/learn-details",
  },
  {
    id: 8,
    name: "Top 10 iPhone Apps to Create Posters: Your 2023 Guide",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/10/Best-Apps-to-Create-Posters-With-iPhone-in-2023.jpg",
    desc: "Are you an iPhone user with a creative spark eager to transform your ideas into striking posters? Well, you’re in for a treat, because the world of poster design is … ",
    path: "/learn-details",
  },
  {
    id: 9,
    name: "10 Best Poster Making Apps for Android in 2023",
    date: "October 31, 2023",
    img: "https://blog.photoadking.com/wp-content/uploads/2023/10/feature-image-poster-maker1-1.jpg",
    desc: "Are you tired of scouring the internet for the best poster making app, only to be overwhelmed by the many options available? Look no further! Creating eye-catching posters for events, … ",
    path: "/learn-details",
  },
];

export default learnData;
